/***********************************************************************/
/*                                                                     */
/*  FILE        :sample3.s                                             */
/*  DESCRIPTION :Sample Testcase for Library Project                   */
/*                                                                     */
/*  This file is generated by e2 studio.                               */
/*                                                                     */
/***********************************************************************/

/***********************************************************************/
/*    File Version: V1.00                                              */
/*    Date Generated: 08/07/2013                                       */
/***********************************************************************/


.text
    .type    _function3, %function


    _function3:

           /* TODO: user code */
                  bx lr

    .end
